---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: "Test GitHub Action 🧪"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions: {}

jobs:
  ### Test the GitHub Action in this Repository ###
  tests:
    name: "Test local GitHub Action"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - name: "Running local action: ${{ github.repository }} 1.2.3"
        uses: $/
        id: plain
        with:
          string: "1.2.3"

      - name: "Error if 1.2.3 rejected"
        if: steps.plain.outputs.valid != 'true'
        shell: bash
        run: |
          # Error if 1.2.3 rejected
          echo "Error: 1.2.3 was rejected as SemVer ❌"
          exit 1

      - name: "Running local action: ${{ github.repository }} v1.2.3"
        uses: $/
        id: v-prefix
        with:
          string: "v1.2.3"

      - name: "Error if v1.2.3 rejected"
        if: steps.v-prefix.outputs.valid != 'true'
        shell: bash
        run: |
          # Error if v1.2.3 rejected
          echo "Error: v1.2.3 was rejected as SemVer ❌"
          exit 1

      # yamllint disable-line rule:line-length
      - name: "Running local action: ${{ github.repository }} 1.2.3-rc.1+build.5"
        uses: $/
        id: pre-release-build
        with:
          string: "1.2.3-rc.1+build.5"

      - name: "Error if pre-release with build metadata rejected"
        if: steps.pre-release-build.outputs.valid != 'true'
        shell: bash
        run: |
          # Error if pre-release with build metadata rejected
          echo "Error: 1.2.3-rc.1+build.5 was rejected as SemVer ❌"
          exit 1

      # yamllint disable-line rule:line-length
      - name: "Running local action: ${{ github.repository }} v1.not-valid.3.garbage [NOT SemVer]"
        uses: $/
        id: garbage
        with:
          string: "v1.not-valid.3.garbage"

      - name: "Error if v1.not-valid.3.garbage accepted"
        if: steps.garbage.outputs.valid != 'false'
        shell: bash
        run: |
          # Error if v1.not-valid.3.garbage accepted
          echo "Error: v1.not-valid.3.garbage was accepted as SemVer ❌"
          exit 1

      # yamllint disable-line rule:line-length
      - name: "Running local action: ${{ github.repository }} 01.2.3 [NOT SemVer]"
        uses: $/
        id: leading-zero
        with:
          string: "01.2.3"

      - name: "Error if leading zero accepted"
        if: steps.leading-zero.outputs.valid != 'false'
        shell: bash
        run: |
          # Error if leading zero accepted
          echo "Error: 01.2.3 was accepted as SemVer ❌"
          exit 1

      # yamllint disable-line rule:line-length
      - name: "Running local action: ${{ github.repository }} 1.2.3-ſ [NOT SemVer]"
        uses: $/
        id: non-ascii-pre-release
        with:
          string: "1.2.3-ſ"

      - name: "Error if non-ASCII pre-release accepted"
        if: steps.non-ascii-pre-release.outputs.valid != 'false'
        shell: bash
        run: |
          # Error if non-ASCII pre-release accepted
          echo "Error: non-ASCII pre-release was accepted as SemVer ❌"
          exit 1

      # yamllint disable-line rule:line-length
      - name: "Running local action: ${{ github.repository }} 1.2.3+ſ [NOT SemVer]"
        uses: $/
        id: non-ascii-build
        with:
          string: "1.2.3+ſ"

      - name: "Error if non-ASCII build metadata accepted"
        if: steps.non-ascii-build.outputs.valid != 'false'
        shell: bash
        run: |
          # Error if non-ASCII build metadata accepted
          echo "Error: non-ASCII build metadata was accepted as SemVer ❌"
          exit 1

      # yamllint disable-line rule:line-length
      - name: "Running local action: ${{ github.repository }} [Override Failure]"
        uses: $/
        id: failure
        continue-on-error: true
        with:
          string: "v1.not-valid.3.garbage"
          exit_on_fail: true

      - name: "Error if step above did NOT fail"
        if: steps.failure.outcome == 'success'
        shell: bash
        run: |
          # Error if step above did NOT fail
          echo "Error: previous test step did NOT fail ❌"
          exit 1

      # yamllint disable-line rule:line-length
      - name: "Running local action: ${{ github.repository }} [Dev tag]"
        uses: $/
        id: dev-tag
        with:
          string: "v1.2.3-dev2"

      - name: "Error if development tag rejected"
        if: steps.dev-tag.outputs.valid != 'true'
        shell: bash
        run: |
          # Error if development tag rejected
          echo "Error: v1.2.3-dev2 was rejected as SemVer ❌"
          exit 1

      - name: "Error if development tag not flagged"
        if: steps.dev-tag.outputs.dev_version != 'true'
        shell: bash
        run: |
          # Error if development tag not flagged
          echo "Error: development tag was not flagged ❌"
          exit 1
